version: '3'

services:
  app:
    build:
      context: .
    command: ["./main", "-config", "config/local.yaml"]
    ports:
      - "8082:8082"
    environment:
      - GO_ENV=development
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app
