version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    command: ["./main", "config/local.yaml"]
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"